alias psgrep="ps wwaux | grep"
alias rm_pyc="find . -name \*\.pyc -exec rm {} \;"
alias mpupdate="sudo port selfupdate && sudo port upgrade outdated && sudo port uninstall inactive"
alias wakup_tuborg="wol 00:E0:18:E5:82:AC"
alias wakup_mediamac="wol 00:26:4A:08:F1:88"